### ISSUE TITLE
Create top level parliment directory for dist

### ISSUE THREAD

**Issue by zacharywhitley** [SemWebCentral/parliament#23]
The distribution zip doesn't have a top level directory. While not required on one likes to download a release and unzip it only to have it puke all over your home directory :)

It's nice to see parliament get a new home and some love. Let me know if there's anything I can do to help out.

**Comment by IanEmmons** [comment]
Thanks for reporting this!

Fixed in commit 1914d7366b3704be325e4a6159749d63c098edb8, 4/25/2019.  Also fixed the executable permissions on the shell scripts, jsvc, and ParliamentAdmin in the distribution zip.
