### ISSUE TITLE
Docker-ize Parliament

### ISSUE THREAD

**Issue by IanEmmons** [SemWebCentral/parliament#3]
Add to the build infrastructure of Parliament a facility that creates a Parliament docker container.

**Comment by panssystem** [comment]
It looks like someone else took on this at some point. See https://github.com/daxid/parliament-triplestore for what seems to be the most up to date of them.

**Comment by daxid** [comment]
Hi, my docker image with parliament is pretty old and relied on the binary versions that were pre-compiled for various systems.

However those binary seem not to be released anymore :-(

**Comment by daxid** [comment]
Good gosh I finally found the releases. I'll upgrade my docker images, probably on Friday...

**Comment by IanEmmons** [comment]
Addressed in most recent pull request.  See "jena/docker/readme.md".
