### ISSUE TITLE
data loader

### ISSUE THREAD

**Issue by hashimkhanwazir** [SemWebCentral/parliament#32]
I want to upload a file of about 15GB. Can you point out command prompt utility for it. As I checked in the bin folder but I could not found it. I am using free version.

**Comment by IanEmmons** [comment]
This is a bug in the documentation, which should mention this command:
```
java -cp "clientJars/*" com.bbn.parliament.jena.joseki.client.RemoteInserter <hostname> <port> <inputfile> [<graph-name>]
```
where "clientJars" is the path name of the directory of that name under your Parliament installation.

**Comment by IanEmmons** [comment]
Reopening pending a fix to the documentation to include the information above.
