### ISSUE TITLE
Release binaries for a couple of systems

### ISSUE THREAD

**Issue by daxid** [SemWebCentral/parliament#36]
Hi,

It is great to see that Parliament has been updated (I thought it was dead !)

Could you please release binaries as there used to be for various systems (ubuntu, centos, mac os and windows used to be available).

Best regards

**Comment by IanEmmons** [comment]
The binaries are present under GitHub's "releases" tab.

**Comment by daxid** [comment]
Damn Github, I was looking for the release tab... but it's not a tab X-D it's "stuff" on the left of the screen...
My bad... I'll update my Docker images then !
