### ISSUE TITLE
Parliament Daemon Shutdown

### ISSUE THREAD

**Issue by IanEmmons** [SemWebCentral/parliament#4]
Understand and document how to make a Parliament daemon on Unix/Linux shut down properly when the machine shuts down (or the daemon controller shuts it down).  Ideally, this understanding should also be turned into scripts for each supported Unix and Linux distro.

**Comment by sadakatsu** [comment]
This could be extended to variants of Linux that do not support System D, but so far our only use cases are for CentOS and Ubuntu.  Both use systemd.
